# Generated by Django 4.0.5 on 2022-06-11 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_item_watch_list_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_item', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='watch_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
