# Generated by Django 4.0.5 on 2022-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_watch_list_item_alter_watch_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bid',
            new_name='starting_price',
        ),
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
            preserve_default=False,
        ),
    ]
