# Generated by Django 4.0.5 on 2022-06-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bid_item_starting_price_item_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='starting_price',
        ),
    ]
